### ISSUE TITLE
Is this plugin able to scrape photos

### ISSUE THREAD

**Issue by Meiqiuclaw** [jellyfin-adult/Jellyfin.Plugin.PhoenixAdultRebirth#115]
I can see the cover photo of metadata while scraping and selecting the metadata. But after my choice, the info of movies changed, without any cover photos.

btw, how to set this plugin？ I only fill PornDb with its API as Default sitename and API token.

emby
latest

**Comment by jellyfin-adult** [comment]
Yes, photos should be available. Could you, please, try to resolve any scene and attach latest logs to this ticket, I'll take a look.
