### ISSUE TITLE
2.1.6.111 is not supported under jellyfin 10.10.10

### ISSUE THREAD

**Issue by JoeMcNuggets** [jellyfin-adult/Jellyfin.Plugin.PhoenixAdultRebirth#125]
**Describe the bug**
After updating to pronium 2.1.6.111 plugin status became "NotSupported" and it is impossible to open plugin's settings

Jellyfin 10.10.10
Plugin Version 2.1.6.111

**Comment by jellyfin-adult** [comment]
@JoeMcNuggets Jellyfin doesn't have version `10.10.10`. Did you mean `10.10.0`? I've installed latest version `10.10.1` and it's working fine there. Could you, please, install the latest version and try again?

**Comment by JoeMcNuggets** [comment]
@jellyfin-adult, yep, my bad, it was meant to be 10.10.0. After upgrading to 10.10.1 plugin started working
