### ISSUE TITLE
Pronium vs PhoenixAdult

### ISSUE THREAD

**Issue by JoeMcNuggets** [jellyfin-adult/Jellyfin.Plugin.PhoenixAdultRebirth#130]
Hello!

jellyfin-adult/Jellyfin.Plugin.Pronium and DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult seem like having the similar codebases, but have no direct git references between

Can you please clarify the relationship between those two code bases and which one should be used?

**Comment by jellyfin-adult** [comment]
Pronium is a fork of `DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult`. I was using `PhoenixAdult` for some time but faced issues, wanted to fix but I've noticed that original repository is sort of abandonded, even valid PRs are not really getting merged. So I've created a fork but then separated it to have separate bug tracker. You can use the one that works for you. But I think `PhoenixAdult` no longer works with latest Emby releases. I'm an Emby user and mostly test in Emby keeping Jellyfin updated.
