### ISSUE TITLE
Rename plugin name to avoid conflicts

### ISSUE THREAD

**Issue by jellyfin-adult** [jellyfin-adult/Jellyfin.Plugin.PhoenixAdultRebirth#2]

**Comment by DirtyRacer1337** [comment]
Also replace uuid

https://github.com/jellyfin-adult/Jellyfin.Plugin.PhoenixAdultRebirth/blob/76d9f4f722ca102a13d8aaf1060e8bc486a3699f/Jellyfin.Plugin.PhoenixAdultRebirth/Plugin.cs#L62

https://github.com/jellyfin-adult/Jellyfin.Plugin.PhoenixAdultRebirth/blob/76d9f4f722ca102a13d8aaf1060e8bc486a3699f/Jellyfin.Plugin.PhoenixAdultRebirth/Configuration/configPage.html#L130
